services:
  - type: web
    name: event-horizon-api
    env: python
    region: oregon
    plan: free
    rootDir: server
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn wsgi:app"
    healthCheckPath: /api/events/featured
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: event-horizon-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: wsgi.py


  - type: static_site
    name: event-horizon-client

    rootDir: client
    buildCommand: "npm install && npm run build"

    publishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: event-horizon-api

          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: event-horizon-db
    region: oregon
    plan: free

